"""empty message

Revision ID: cb4cd279b09c
Revises: 
Create Date: 2018-08-07 15:28:01.370689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4cd279b09c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('award',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_last_name', sa.String(length=64), nullable=True),
    sa.Column('pi_first_name', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.String(length=128), nullable=True),
    sa.Column('pi_email', sa.String(length=128), nullable=True),
    sa.Column('organization', sa.String(length=128), nullable=True),
    sa.Column('program', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('award_number', sa.Integer(), nullable=True),
    sa.Column('pervasive_data', sa.Boolean(), nullable=True),
    sa.Column('data_science', sa.Boolean(), nullable=True),
    sa.Column('big_data', sa.Boolean(), nullable=True),
    sa.Column('case_study', sa.Boolean(), nullable=True),
    sa.Column('data_synonyms', sa.Text(), nullable=True),
    sa.Column('not_relevant', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('award')
    op.drop_table('user')
    # ### end Alembic commands ###
