"""empty message

Revision ID: e93de275c40e
Revises: 
Create Date: 2018-12-21 15:03:43.825387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93de275c40e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.Integer(), nullable=True),
    sa.Column('pi_name', sa.String(length=300), nullable=True),
    sa.Column('contact', sa.String(length=1000), nullable=True),
    sa.Column('pi_email', sa.String(length=128), nullable=True),
    sa.Column('organization', sa.String(length=1000), nullable=True),
    sa.Column('program', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('award_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('award_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code_type', sa.String(length=45), nullable=True),
    sa.Column('pervasive_data', sa.Boolean(), nullable=True),
    sa.Column('data_science', sa.Boolean(), nullable=True),
    sa.Column('big_data', sa.Boolean(), nullable=True),
    sa.Column('case_study', sa.Boolean(), nullable=True),
    sa.Column('data_synonyms', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['award_id'], ['award.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code')
    op.drop_table('user')
    op.drop_table('award')
    # ### end Alembic commands ###
